### ISSUE TITLE
Is it possible to set read_only=2 for playground dataset?

### ISSUE THREAD

**Issue by tisonkun** [ClickHouse/github-explorer#12]
@alexey-milovidov I follow the document to connect clickhouse from metabase: https://clickhouse.com/docs/en/connect-a-ui/metabase-and-clickhouse/

Although, it fails to connect due to it runs several settings queries and it seems playground set read_only=1.

This can be a major reason I have to prepare my own dataset QAQ.

**Comment by alexey-milovidov** [comment]
It will be solved in #40244.

Although simply allowing `readonly=2` is not possible, because we don't want limits to be overridden, and also it will allow table functions, which is not good due to SSRF.

**Comment by tisonkun** [comment]
@alexey-milovidov I can still see this issue:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/18818196/186556705-0779cd63-370d-4668-8ba3-f0cbb8a886d4.png">

```
ClickHouse exception, code: 1002, host: play.clickhouse.com, port: 443; Code: 164. DB::Exception: Cannot modify 'result_overflow_mode' setting in readonly mode. (READONLY) (version 22.8.1.1231 (official build))
```

**Comment by alexey-milovidov** [comment]
@tisonkun This issue has been answered, hence closing.

**Comment by tisonkun** [comment]
Got it.
