### ISSUE TITLE
How to get all existing commit SHA hashes from a repo?

### ISSUE THREAD

**Issue by ImVantexHD** [ClickHouse/github-explorer#19]
Hi @alexey-milovidov,

I have a repo, for example: https://github.com/tachiyomiorg/tachiyomi-extensions/tree/repo
I am looking for a query to pull data from the GH archive [dataset](https://clickhouse-public-datasets.s3.amazonaws.com/github_events/tsv/github_events_v3.tsv.xz) to extract SHA commit hashes from PushEvent records
I need the output to be in this format:

{created_at} https://github.com/tachiyomiorg/tachiyomi-extensions/tree/{sha}
2021-03-01 https://github.com/tachiyomiorg/tachiyomi-extensions/tree/37307e29cc91ae10afd322dfc31f65cc7c175f6a

i tried this but is not showing the sha, only the date and url, can you help me modify it?:
`SELECT created_at, format('https://github.com/{}/tree/{}', repo_name, number::String, 'sha') AS url FROM github_events WHERE event_type = 'PushEvent' AND repo_name LIKE 'tachiyomiorg/%' ORDER BY created_at DESC`

**Comment by alexey-milovidov** [comment]
If I recall correctly, it is not possible to do with this dataset.

The reason: PushEvent contains an array with a limited number of commits, e.g. maximum 100 items.
(I hope I remembered it correctly, but consult the docs of GitHub API)
