### ISSUE TITLE
Some questions about GitHub dataset in Clickhouse

### ISSUE THREAD

**Issue by frank-zsy** [ClickHouse/github-explorer#9]
Hello, I am also very interested in GitHub event data and using them with Clickhouse for research purpose.

Here is some question about the dataset and setup of database.

- In my practice, to put all event logs into one table will be quite slow if the number of rows grows to 1 billion. Is something I missed here. Will the `order by` in create table clause help and if it will be more quicker if I add `partition toYYYYMM(created_at)` to part the data by month?
- I also notice that there will be some duplicate data in different raw data file like maybe several rows about o'clock will be in both adjacent files. Since there is no primary key in Clickhouse, how could we avoid this?
- You use `LowCardinality` on `repo_name` and `actor_login`, but by official suggestion, we should use it if the distinct values count is under 100,000 , but the `repo_name` and `actor_login` are more than 10 million on GitHub, will this perform better than ordinary string type?

Thanks for the project.

**Comment by stas-sl** [comment]
Regarding LowCardinality, you might find a useful discussion here https://github.com/ClickHouse/ClickHouse/issues/36428 

As for github_events table, its sorting keys are: `(event_type, repo_name, created_at)`, which means repeated values in columns repo_name and actor_login will be placed nearby, and single dictionary could be used for encoding large ranges of rows. So in this case LC might work quite well, despite much larger number of distinct values globally.

**Comment by frank-zsy** [comment]
@stas-sl Thanks, I am not quite familiar with the underlying implementation of CH, I will learn and maybe I will do some benchmark on this dataset too. Thanks.

**Comment by alexey-milovidov** [comment]
@frank-zsy 

> In my practice, to put all event logs into one table will be quite slow if the number of rows grows to 1 billion.

ClickHouse work well if you pull all data into one table. It does not matter how many records do you have.
Partitions are also unneeded.

As long as you have appropriate sorting key, it will work alright and there is no reason in making many tables.

(Note: using many tables is a practice someone may learn working with MySQL, Hadoop, Spark, Bigquery and other obsolete systems that don't have incremental data ordering).

> I also notice that there will be some duplicate data in different raw data file like maybe several rows about o'clock will be in both adjacent files. Since there is no primary key in Clickhouse, how could we avoid this?

You can run `OPTIMIZE TABLE github_events FINAL DEDUPLICATE` or `OPTIMIZE TABLE github_events FINAL DEDUPLICATE BY fields...`

> You use LowCardinality on repo_name and actor_login, but by official suggestion, we should use it if the distinct values count is under 100,000 , but the repo_name and actor_login are more than 10 million on GitHub, will this perform better than ordinary string type?

\+ to @stas-sl, it matters if data is locally low cardinality, so if say, for every 10 million adjacent values there are not more than 100 000 unique values.
